name: graphql_codegen_example
description: Simple example using graphql_flutter and graphql_codegen with Relay-like structure

publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1 # If you wish to use hooks, like the ones generated for graphql operations
  graphql: ^5.1.2-beta.4
  graphql_flutter: ^5.1.1-beta.4
  provider: ^6.0.3 # Using in this example for cache updating

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0 # Used with graphql_codegen for generating Dart type files
  graphql_codegen: ^0.11.0-beta.4 # graphql_codegen is only used for the generation, so it isn't needed run-time



flutter:
  uses-material-design: true
